import { SchemaType } from './Context/PropContext/type';

export const sampleJsonField: SchemaType[] = [
  {
    fieldWidth: 1 / 3,
    key: 'CheckBoxGroupCheck',
    fieldLabel: {
      label: 'General Details',
      placeholderText: 'Enter Date Screening Provided',
      description: 'some description about the field',
    },
    fieldType: 'title',
    isRequired: true,
  },
  {
    fieldWidth: 1 / 2,
    key: 'Des',
    fieldLabel: {
      label: 'some description about the form',
      placeholderText: 'Enter Date Screening Provided',
      description: 'some description about the field',
    },
    fieldType: 'description',
    isRequired: true,
  },
  {
    fieldWidth: 1 / 2,
    key: 'DateScreeningProvided',
    fieldLabel: {
      label: 'Date Screening Provided',
      placeholderText: 'Enter Date Screening Provided',
      description: 'some description about the field',
    },
    fieldType: 'textArea',
    isRequired: false,
  },
  {
    fieldWidth: 1 / 2,
    key: 'testCheckboxes',
    fieldLabel: {
      label: 'Date Screening Provided',
      placeholderText: 'Enter Date Screening Provided',
      description: 'some description about the field',
    },
    fieldType: 'checkboxes',
    options: [{ 'key': 'MondayDay', 'label': 'Monday Day' }, { 'key': 'Tuesday', 'label': 'Tuesday' }, { 'key': 'Wednesday', 'label': 'Wednesday' }, { 'key': 'Thursday', 'label': 'Thursday' }, { 'key': 'Friday', 'label': 'Friday' }, { 'key': 'Saturday', 'label': 'Saturday' }, { 'key': 'Sunday', 'label': 'Sunday' }],
    isRequired: false,
  },
  {
    fieldWidth: 1 / 2,
    key: 'VisionDetails',
    fieldLabel: {
      label: 'Vision Details',
      placeholderText: 'Enter Date Screening Provided',
      description: 'some description about the field',
    },
    fieldType: 'title',
    isRequired: true,
  },
  {
    fieldWidth: 1 / 2,
    key: 'LeftEye',
    fieldLabel: {
      label: 'Left Eye',
      placeholderText: 'Enter Date Screening Provided',
      description: 'some description about the field',
    },
    fieldType: 'label',
    isRequired: false,
  },
  {
    fieldWidth: 1,
    key: 'LeftFar',
    fieldLabel: {
      label: 'Far',
      placeholderText: 'Enter Date Screening Provided',
      description: 'some description about the field',
    },
    fieldType: 'checkbox',
    isRequired: false,
  },
  {
    fieldWidth: 1,
    key: 'LeftNear',
    fieldLabel: {
      label: 'Near',
      description: '',
      placeholderText: '',
    },
    disable: false,
    fieldType: 'checkbox',
    isRequired: false,
  },
  {
    fieldWidth: 1,
    key: 'LeftEyeDetails',
    fieldLabel: {
      label: 'Left Eye Details',
      description: '',
      placeholderText: '',
    },
    fieldType: 'textField',
    isRequired: true,
    validation: {
      validation: 'number',
    },
  },
  {
    fieldWidth: 1 / 2,
    dependentParentLabel: 'LeftFar',
    ifValueIs: true,
    key: 'VisionLeftFar',
    fieldLabel: {
      label: 'Vision Left Far',
      description: '',
      placeholderText: '',
    },
    fieldType: 'select',
    options: [{ 'key': '20/20', 'label': '20/20' }, { 'key': '20/30', 'label': '20/30' }, { 'key': '20/40', 'label': '20/40' }],
    isRequired: true,
  },
  {
    fieldWidth: 1 / 2,
    dependentParentLabel: 'LeftNear',
    ifValueIs: true,
    key: 'VisionLeftNear',
    fieldLabel: {
      label: 'Vision Left Near',
      description: '',
      placeholderText: '',
    },
    fieldType: 'select',
    options: [{ 'key': '20/20', 'label': '20/20' }, { 'key': '20/30', 'label': '20/30' }, { 'key': '20/40', 'label': '20/40' }],
    isRequired: true,
  },
  {
    fieldWidth: 1 / 2,
    key: 'RightEye',
    fieldLabel: {
      label: 'Right Eye',
      description: '',
      placeholderText: '',
    },
    fieldType: 'subTitle',
    isRequired: false,
  },
  {
    fieldWidth: 1 / 2,
    key: 'RightFar',
    fieldLabel: {
      label: 'Far',
      description: '',
      placeholderText: '',
    },
    fieldType: 'checkbox',
    isRequired: false,
  },
  {
    fieldWidth: 1 / 2,
    key: 'RightNear',
    fieldLabel: {
      label: 'Near',
      description: '',
      placeholderText: '',
    },
    fieldType: 'checkbox',
    isRequired: false,
  },
  {
    fieldWidth: 1 / 2,
    key: 'RightEyeDetails',
    fieldLabel: {
      label: 'Right Eye Details',
      description: '',
      placeholderText: '',
    },
    fieldType: 'textField',
    isRequired: true,
  },
  {
    fieldWidth: 1 / 2,
    dependentParentLabel: 'RightFar',
    ifValueIs: true,
    key: 'VisionRightFar',
    fieldLabel: {
      label: 'Vision Right Far',
      description: '',
      placeholderText: '',
    },
    fieldType: 'select',
    options: [{ 'key': '20/20', 'label': '20/20' }, { 'key': '20/30', 'label': '20/30' }, { 'key': '20/40', 'label': '20/40' }],
    isRequired: true,
  },
  {
    fieldWidth: 1 / 2,
    dependentParentLabel: 'RightNear',
    ifValueIs: true,
    key: 'VisionRightNear',
    fieldLabel: {
      label: 'Vision Right Near',
      description: '',
      placeholderText: '',
    },
    fieldType: 'select',
    options: [{ 'key': '20/20', 'label': '20/20' }, { 'key': '20/30', 'label': '20/30' }, { 'key': '20/40', 'label': '20/40' }],
    isRequired: true,
  },
  {
    fieldWidth: 1 / 2,
    key: 'Ishihara',
    fieldLabel: {
      label: 'Ishihara',
      placeholderText: 'Enter Ishihara',
      description: 'some description about the field',
    },
    fieldType: 'select',
    isRequired: true,
    options: [{ 'key': 'Passed', 'label': 'Passed' }, { 'key': 'Failed', 'label': 'Failed' }],
  },
  {
    fieldWidth: 0.3333,
    key: 'Random-DotE',
    fieldLabel: {
      label: 'Random-Dot E',
      placeholderText: 'Enter Random-Dot E',
      description: 'some description about the field',
    },
    fieldType: 'select',
    isRequired: false,
    options: [{ 'key': 'Passed', 'label': 'Passed' }, { 'key': 'Failed', 'label': 'Failed' }],
  },
  {
    fieldWidth: 0.3333,
    key: 'ColorBlindness',
    fieldLabel: {
      label: 'Select Blindness',
      placeholderText: 'Enter Color Blindness',
      description: 'some description about the field',
    },
    fieldType: 'select',
    isRequired: false,
    options: [{ 'key': 'Passed', 'label': 'Passed' }, { 'key': 'Failed', 'label': 'Failed' }],
  },
  {
    fieldWidth: 0.3333,
    key: 'Binocularity',
    fieldLabel: {
      label: 'Binocularity',
      placeholderText: 'Select Binocularity',
      description: 'some description about the field',
    },
    fieldType: 'select',
    isRequired: false,
    options: [{ 'key': 'Passed', 'label': 'Passed' }, { 'key': 'Failed', 'label': 'Failed' }],
  },
  {
    fieldWidth: 1 / 2,
    key: 'DepthTest/PlusLenses',
    fieldLabel: {
      label: 'Depth Test/Plus Lenses',
      placeholderText: 'Select Depth Test/Plus Lenses',
      description: 'some description about the field',
    },
    fieldType: 'select',
    isRequired: false,
    options: [{ 'key': 'Passed', 'label': 'Passed' }, { 'key': 'Failed', 'label': 'Failed' }],
  },
  {
    fieldWidth: 1 / 2,
    key: 'Glasses/Lens',
    fieldLabel: {
      label: 'Glasses/Lens',
      placeholderText: 'Select Glasses/Lens',
      description: 'some description about the field',
    },
    fieldType: 'select',
    isRequired: false,
    options: [{ 'key': 'Passed', 'label': 'Passed' }, { 'key': 'Failed', 'label': 'Failed' }],
  },
  {
    fieldWidth: 1 / 2,
    key: 'VisionAid',
    fieldLabel: {
      label: 'Vision Aid',
      description: '',
      placeholderText: '',
    },
    fieldType: 'textField',
    isRequired: false,
  },
  {
    fieldWidth: 1 / 2,
    key: 'Note',
    fieldLabel: {
      label: 'Note',
      placeholderText: 'Enter Note',
      description: '',
    },
    fieldType: 'textField',
    isRequired: false,
  },
  {
    fieldWidth: 1 / 2,
    key: 'PhysicianExamDetails',
    fieldLabel: {
      label: 'Physician Exam Details',
      description: '',
      placeholderText: '',
    },
    fieldType: 'title',
    isRequired: false,
  },
  {
    fieldWidth: 1 / 2,
    key: 'ExamConductedBy',
    fieldLabel: {
      label: 'Exam Conducted By',
      description: '',
      placeholderText: '',
    },
    fieldType: 'select',
    options: [{ 'key': 'SchoolNurse', 'label': 'School Nurse' }, { 'key': 'FamilyPhysician', 'label': 'Family Physician' }],
    isRequired: false,
  },
  {
    fieldWidth: 1 / 2,
    key: 'ExamConductedByRadio',
    fieldLabel: {
      label: 'Exam Conducted By Radio',
      description: '',
      placeholderText: '',
    },
    fieldType: 'radio',
    options: [{ 'key': 'SchoolNurse', 'label': 'School Nurse' }, { 'key': 'FamilyPhysician', 'label': 'Family Physician' }],
    isRequired: false,
  },
  {
    fieldWidth: 1 / 2,
    key: 'ScreeningOutcome',
    fieldLabel: {
      label: 'Screening Outcome',
      description: '',
      placeholderText: '',
    },
    fieldType: 'select',
    options: [{ 'key': 'Pass', 'label': 'Pass' }, { 'key': 'Fail', 'label': 'Fail' }, { 'key': 'Missed', 'label': 'Missed' }],
    isRequired: false,
  },
  {
    fieldWidth: 1 / 2,
    dependentParentLabel: 'ScreeningOutcome',
    ifValueIs: 'Fail',
    key: 'ReferredForEvaluation/Treatment',
    fieldLabel: {
      label: 'Referred For Evaluation/Treatment',
      description: '',
      placeholderText: '',
    },
    fieldType: 'radio',
    isRequired: true,
    options: [{ 'key': 'Yes', 'label': 'Yes' }, { 'key': 'No', 'label': 'No' }],
  },
  {
    fieldWidth: 1 / 2,
    dependentParentLabel: 'ReferredForEvaluation/Treatment',
    ifValueIs: 'Yes',
    key: 'ReferredForEvaluation/TreatmentDatetime',
    fieldLabel: {
      label: 'Completed Referrals Reported date time',
      placeholderText: 'Enter Completed Referrals Reported date time',
      description: 'some description about the field',
    },
    fieldType: 'time',
    isRequired: true,
  },
  {
    fieldWidth: 1 / 2,
    dependentParentLabel: 'ReferredForEvaluation/Treatment',
    ifValueIs: 'Yes',
    key: 'CompletedReferralsReported',
    fieldLabel: {
      label: 'Completed Referrals Reported',
      description: '',
      placeholderText: '',
    },
    fieldType: 'radio',
    isRequired: false,
    options: [{ 'key': 'Yes', 'label': 'Yes' }, { 'key': 'No', 'label': 'No' }],
  },
  {
    fieldWidth: 1 / 2,
    dependentParentLabel: 'CompletedReferralsReported',
    ifValueIs: 'Yes',
    key: 'CompletedReferralsReporteddatetime',
    fieldLabel: {
      label: 'Completed Referrals Reported Datetime',
      description: '',
      placeholderText: '',
    },
    fieldType: 'textField',
    isRequired: true,
    validation: {
      validation: 'number',
      max: 10,
      min: 5,
    },
  },
  {
    fieldWidth: 1 / 2,
    key: 'CompletedReferralsReport',
    fieldLabel: {
      label: 'Completed Referrals Report',
      description: '',
      placeholderText: '',
    },
    fieldType: 'file',
    isRequired: false,
    validation: {
      fileType: ['jpeg', 'jpg', 'png'],
    },
  },
  {
    fieldWidth: 1 / 2,
    key: 'singleFile',
    fieldLabel: {
      label: 'Completed Referrals Report',
      description: '',
      placeholderText: '',
    },
    fieldType: 'file',
    isRequired: true,
    validation: {
      fileType: ['jpeg', 'jpg', 'png'],
    },
  },
  {
    fieldWidth: 1 / 2,
    key: 'date-test',
    fieldLabel: {
      label: 'Completed Referrals Report',
      description: '',
      placeholderText: '',
    },
    fieldType: 'date',
    isRequired: true,
  },
  {
    fieldWidth: 1 / 3,
    key: 'customField',
    fieldLabel: {
      label: 'General Details',
      placeholderText: 'Enter Date Screening Provided',
      description: 'some description about the field',
    },
    fieldType: 'title',
    isRequired: true,
  },
];

