name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'packages/**/package-lock.json'
      - run: npm install
      - run: npm run clean
      - run: npm run bootstrap
      - run: npm run cs-format
      - run: npm run cs-check
      - run: npm run build

      # - name: Build with Netlify badge

      - if: matrix.node-version == '18.x'
        uses: actions/upload-artifact@v3
        with:
          name: playground
          path: packages/playground/dist
          
      - if: matrix.node-version == '18.x'
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: packages/docs/build

  deploy_playground_and_docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    name: Deploy playground and docs to GitHub Pages
    needs: [build]
    steps:
      - name: Download built playground
        uses: actions/download-artifact@v3
        with:
          name: playground
          path: dist
      - name: Download built docs
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: dist/docs
      - name: Deploy playground + docs to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          keep_history: true
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}